#!/usr/bin/env bash

VERSION="0.1.0"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
VM_NAME="sr_web_dev.${VERSION}"
TFTP_DIR="${HOME}/Library/VirtualBox/TFTP"
LINUX_ISO="${HOME}/tftpboot/CentOS-7.0-1406-x86_64-Minimal.iso"
LINUX_DIR="${HOME}/tftpboot/CentOS-7.0-1406-x86_64-Minimal"
SYSLINUX="${HOME}/tftpboot/syslinux-4.07"
IPXE="${DIR}/tftpboot/ipxe.pxe"

VBoxManage showvminfo "${VM_NAME}" > /dev/null 2>&1 \
    && VBoxManage unregistervm "${VM_NAME}" --delete

VBoxManage createvm \
    --name "${VM_NAME}" \
    --ostype "RedHat_64" \
    --register

# Extract some machine settings as variables:
eval $(VBoxManage showvminfo "${VM_NAME}" --machinereadable | grep CfgFile)
eval $(VBoxManage showvminfo "${VM_NAME}" --machinereadable | grep UUID)

VM_DIR=$(dirname "$CfgFile")
VM_HD="${VM_DIR}/${VM_NAME}.vdi"
VM_TFTP_DIR="${TFTP_DIR}/${UUID}/pxelinux.cfg"

mkdir -p "${VM_TFTP_DIR}"

rm -f "${TFTP_DIR}/${UUID}/pxelinux.0"
rm -f "${TFTP_DIR}/${UUID}/linux"
rm -f "${TFTP_DIR}/${VM_NAME}.pxe"
rm -f "${VM_TFTP_DIR}/default"

ln -s "${SYSLINUX}/core/pxelinux.0" "${TFTP_DIR}/${UUID}/pxelinux.0"
ln -s "${LINUX_DIR}"                "${TFTP_DIR}/${UUID}/linux"
ln -s "${DIR}/tftpboot/ipxe.pxe"    "${TFTP_DIR}/${VM_NAME}.pxe"
ln -s "${DIR}/tftpboot/pxe_menu"    "${VM_TFTP_DIR}/default"

VBoxManage modifyvm "${VM_NAME}" \
  --memory 1024 \
  --vram 10 \
  --ioapic on \
  --pae on \
  --hwvirtex on \
  --nestedpaging on \
  --vtxvpid on \
  --cpus 2 \
  --rtcuseutc on \
  --boot1 disk \
  --boot2 net \
  --boot3 dvd \
  --boot4 none \
  --nic1 nat \
  --nictype1 82540EM \
  --audio none \
  --usb off

VBoxManage storagectl "${VM_NAME}" \
  --name "IDE" \
  --add "ide" \
  --controller "ICH6" \
  --hostiocache on \
  --bootable on

VBoxManage storageattach "${VM_NAME}" \
  --storagectl "IDE" \
  --type dvddrive \
  --port 0 \
  --device 0 \
  --medium "${LINUX_ISO}"

VBoxManage storagectl "${VM_NAME}" \
  --name "SATA" \
  --add "sata" \
  --controller "IntelAhci" \
  --hostiocache on \
  --bootable on

VBoxManage createhd \
  --filename "${VM_HD}" \
  --size 28610 \
  --format VDI \
  --variant Standard

VBoxManage storageattach "${VM_NAME}" \
  --storagectl "SATA" \
  --type hdd \
  --port 0 \
  --device 0 \
  --medium "${VM_HD}"
